---
label: config.yaml
hide_body: true
fields:
- type: text
  name: twitter
  label: twitter
- type: text
  name: github
  label: github
- type: text
  name: linkedin
  label: linkedin
- type: text
  name: youtube
  label: youtube
- type: text
  name: dribbble
  label: dribbble
- type: text
  name: instagram
  label: instagram
- type: text
  name: facebook
  label: facebook
- type: text
  name: medium
  label: medium
- type: text
  name: patreon
  label: patreon
- type: text
  name: paypal
  label: paypal
- type: text
  name: unsplash
  label: unsplash
